<?php defined('SYSPATH') OR die('No direct access allowed.');
$config['site']=array (
  	'type' => 1,
  	'site_title' => '上海竞搏科技',
	'site_title2' => '竞搏科技',
  	'site_email' => 'webmaster@jingbo365.com',
	'site_email2' => 'siyew@jingbo365.com',
  	'name' => 'www.jingbo-hitech.com',
  	'domain' => 'jingbo-hitech.com',
	'keywords' => '竞搏,竞搏科技',
	'description' => '上海竞搏信息科技有限公司成立于2010年，位于国际化大都市上海，注册资金5000万元，是一家专业从事光电产品、节能设备的技术开发、技术服务、技术转让、技术咨询，以及照明系统的设计安装，节能环保工程的承接和综合技术服务为一体的高新技术和综合运营服务企业',
	'kf_phone_num' => '400-820-2324',
	'kf_phone_num2' => '021-61176880',
	'cz_phone_num' => '021-61176883',
	'copyright' => 'Copyright © 2010-2011',
	'company_name' => '上海竞搏信息科技有限公司',
	'icp' => '沪ICP备11025247号',
  	'logo' => NULL,
  	'twitter' => 'Twitter链接设置',
  	'facebook' => 'Facebook链接设置',
  	'youtube' => 'Youtube链接设置',
  	'trustwave' => 'Trustwave链接设置',
  	'macfee' => 'Macfee代码',
  	'livechat' => 'livechat代码',
  	'head_code' => '',
  	'body_code' => '',
  	'index_code' => '',
  	'product_code' => '',
  	'payment_code' => '',
  	'pay_code' => '',
  	'register_mail_active' => '0',
  	'register_mail_check_pwd' => '!@DFsdfas12!@#!',    //验证邮箱密钥
  	'min_draw_money' => 1,         //最低提现金额
  	'max_draw_money' => 10000,     //最高底线金额
  	'max_day_draw_count' => 3,     //每日最高提现次数
  	'draw_money_ratio' => 30,      //提现本金消费比率
  	'draw_money_fee' => 10,        //提现本金超出本金消费比率的手续费
  	'alipay_account' => 'siyewang@sina.com',     //支付宝付款帐号
);
$config['site_en']=array (
		'type' => 1,
		'site_title' => '竞搏LED',
		'site_title2' => '竞搏',
		'site_email' => 'webmaster@jingbo365.com',
		'site_email2' => 'siyew@jingbo365.com',
		'name' => 'www.jingbo-hitech.com',
		'domain' => 'jingbo-hitech.com',
		'keywords' => '竞搏,LED',
		'description' => '上海竞搏信息科技有限公司成立于2010年，位于国际化大都市上海，注册资金5000万元，是一家专业从事光电产品、节能设备的技术开发、技术服务、技术转让、技术咨询，以及照明系统的设计安装，节能环保工程的承接和综合技术服务为一体的高新技术和综合运营服务企业',
		'kf_phone_num' => '400-820-2324',
		'kf_phone_num2' => '021-61176880',
		'cz_phone_num' => '021-61176883',
		'copyright' => 'Copyright © 2010-2011',
		'company_name' => 'Shanghai Jingbo Information &Technology limited company',
		'icp' => '沪ICP备11025247号',
		'logo' => NULL,
		'twitter' => 'Twitter链接设置',
		'facebook' => 'Facebook链接设置',
		'youtube' => 'Youtube链接设置',
		'trustwave' => 'Trustwave链接设置',
		'macfee' => 'Macfee代码',
		'livechat' => 'livechat代码',
		'head_code' => '',
		'body_code' => '',
		'index_code' => '',
		'product_code' => '',
		'payment_code' => '',
		'pay_code' => '',
		'register_mail_active' => '0',
		'register_mail_check_pwd' => '!@DFsdfas12!@#!',    //验证邮箱密钥
		'min_draw_money' => 1,         //最低提现金额
		'max_draw_money' => 10000,     //最高底线金额
		'max_day_draw_count' => 3,     //每日最高提现次数
		'draw_money_ratio' => 30,      //提现本金消费比率
		'draw_money_fee' => 10,        //提现本金超出本金消费比率的手续费
		'alipay_account' => 'siyewang@sina.com',     //支付宝付款帐号
);
$config['match'] = array(
    'jczq_endtime' => 60*19, //竞彩足球截止购买时间 截止时间减去此处时间
	'jczq_endtime_ds' => 60*24, //竞彩足球单式截止购买时间 截止时间减去此处时间
    'jclq_endtime' => 60*19, //竞彩篮球截止购买时间 截止时间减去此处时间
	'bjdc_endtime' => 60*19, //北京单场截止购买时间 截止时间减去此处时间
	'zcsf_endtime' => 60*20, //足彩胜负截止购买时间 截止时间减去此处时间
	//'zcsf_endtime' => 60*1000000, //足彩胜负截止购买时间 截止时间减去此处时间
	'zcsf_endtime_ds' => 60*25, //足彩胜负单式截止购买时间 截止时间减去此	
	//'zcsf_endtime_ds' => 60*4000000, //足彩胜负单式截止购买时间 截止时间减去此	
);
$config['front_path'] = '/usr/local/cp/front'; //系统前台根目录
$config['hm_sd'] = array(
	'sd_userid' => 2352,//系统收底帐号id
	'sd_limit_buyed' => 0.9,//合买达90%及以上系统收底
);